### ISSUE TITLE
Title的设置

### ISSUE THREAD

**Issue by wulitaotao** [7449/BannerLayout#1]
你的那个title的颜色不能设置，位置和小圆点位置重叠，这可以提供接口，让用户设置，而且不支持扩展，希望可以更改

**Comment by 7449** [comment]
title的颜色可以设置，忘了写set方法了 xml里面可以设置，小圆点和title的位置都可以自己选择设置左边右边还是中间  ，如果titile和小圆点的位置不一样， title和小圆点重叠就是因为文字太长了，由于title的长度不固定，所以文字的长度应该交给使用者设置，
你说的扩展是什么？
现在已经可以由用户自己addView提示栏，不过我感觉这样作用不大，用封装的就是为了方便，
