### ISSUE TITLE
Whats happened if items count be too large (Question)

### ISSUE THREAD

**Issue by IRMobydick** [7449/BannerLayout#10]
Hi there,
First of all thanks for this handy and useful library 👍 

Some questions:
1. can you share `proguard` rules?
2. if items count be too large ( like 20 or greater!) whats happened to pager indicator dots?
Is there any chance to get behavior like instagram?

thanks :)

**Comment by 7449** [comment]
Being overtime ...

**Comment by 7449** [comment]
* keep class com.bannerlayout.**{*;}

   * dots.getCount>=20?  Is there a screenshot or git?  let me see

perhaps you can set the width and height of the dots according to the density of the screen,

      BannerLayout.setDotsWidthAndHeight()   or   BannerLayout.setDotsMargin()

**Comment by IRMobydick** [comment]
Thanks for replying
Well, yeah in some case we get data with dots.getCount >= 20! like this!
![screenshot_20170725-165518](https://user-images.githubusercontent.com/4468890/28572135-f6d5bd0c-715a-11e7-9abe-cc5587e4d67a.jpg)

At this image we got 28 image as gallery!

Is there any change to set limit for dots to scroll dots holder area like instagram app?!
Another thing, if item be exactly 1, what happened? dot should appear? banner should get scroll?

**Comment by 7449** [comment]
see：  https://github.com/7449/BannerLayout/blob/master/app/src/main/java/com/bannersimple/simple/issues/Issues10Activity.java

this may be what you want

**Comment by IRMobydick** [comment]
Thanks Bro. I'll check it now! 👍

**Comment by IRMobydick** [comment]
Ummmm... that was not exactly what i want dude :(
You just change size of dots base on screen width and still, if items count be so large, dots size goes to be so small!!
BTW thanks for effort 🙏 
I'll try to overcome this issue and share it here :)

**Comment by 7449** [comment]
I installed instagram and did not see banner，so I do not know what you want the effect

**Comment by IRMobydick** [comment]
Check this out:
https://www.instagram.com/p/BW8kTLNlCXE/
![photo_2017-07-26_11-23-41](https://user-images.githubusercontent.com/4468890/28608262-eea5f328-71f4-11e7-8c37-666705a836a5.jpg)

**Comment by 7449** [comment]
animations need your own implementation, this is just a simple example🤔🤔
