### ISSUE TITLE
能否像淘宝那样，第一页是视频。

### ISSUE THREAD

**Issue by pengjunhong** [7449/BannerLayout#14]

**Comment by 7449** [comment]
如果是指静态图片，只是中间有个视频播放按钮，点进去视频播放是可以的
如果banner播放视频那不支持
但是BannerRootView是FrameLayout，所以可以add自己的View,比较麻烦

**Comment by pengjunhong** [comment]
嗯 效果是想要直接支持视频播放的情况，我这边在好好研究源码下。
