### ISSUE TITLE
auto start and rotate not work

### ISSUE THREAD

**Issue by leanggithub** [7449/BannerLayout#15]
compileSdkVersion,target 28

 bannerLayout
                .delayTime(3000)
                .setOnBannerImageLoader(GlideImageLoader())
                .resource(adapter)
//                .addTipLayout(BannerTip(
//                        dotSelector = R.drawable.selector_banner_dots,
//                        dotSite = BannerTipLayout.CENTER,
//                        tipWidth = BannerLayout.MATCH_PARENT,
//                        dotWidth = 30,
//                        dotHeight = 30,
//                        tipHeight = 60))
                .addOnItemClickListener<SimpleBannerInfo> { view, _, info ->
                    val openURL = Intent(Intent.ACTION_VIEW)
                    openURL.data = Uri.parse(info.title)
                    startActivity(openURL)
                }

// xml
 <com.android.banner.BannerLayout
        android:id="@+id/bannerLayout"
        android:layout_width="match_parent"
        android:layout_height="150dp"
        app:banner_guide="true"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
same your exam.

**Comment by 7449** [comment]
<com.android.banner.BannerLayout
android:layout_width="match_parent"
android:layout_height="150dp"
~~app:banner_guide="true"~~ />


guide applies to start page guidance, not banner

**Comment by leanggithub** [comment]
thank you
