### ISSUE TITLE
垂直轮播？

### ISSUE THREAD

**Issue by ruhaly** [7449/BannerLayout#2]
可以支持垂直轮播？

**Comment by 7449** [comment]
要确定是什么样的效果？ 单单的一个垂直轮播很简单，但是如果还要加上小圆点和title 之类的 在现有的框架上更改就比较复杂了

**Comment by 7449** [comment]
如果title 和小圆点的位置还是底部 那我这边加个判断就支持垂直轮播，如果这两个位置要变成竖直排列的话就比较复杂

**Comment by ruhaly** [comment]
我准备做textView垂直跑马灯效果的，

**Comment by 7449** [comment]
我想了下可以提供垂直轮播的功能，控件提供了addPromptBar这个方法可以自己添加提示栏，至于里面的内容由使用者自行决定，你可以先试下addPromptBar这个方法，如果要小圆点的话，就必须要接管onBannerPageChangeListener

**Comment by 7449** [comment]
垂直轮播用的是动画 没用自定义控件  你可以看下

**Comment by ruhaly** [comment]
怎么设置垂直

**Comment by 7449** [comment]
simple有完整示例

**Comment by ruhaly** [comment]
顺便问下 有什么刷新 加载控件推荐，最好可以独立开来，不是集成recycleview的

**Comment by 7449** [comment]
https://github.com/7449/AndroidDevelop/tree/master/RefreshLayout


https://github.com/7449/XAdapter
