### ISSUE TITLE
轮播往回滑动会出现ANR

### ISSUE THREAD

**Issue by huangqiongbin** [7449/BannerLayout#6]

**Comment by 7449** [comment]
什么情况下出现anr了?我这边并没有这个问题

**Comment by huangqiongbin** [comment]
。。。不好意思。查找了一下，是因为想用暂停轮播，然后直接调用start(false)，然后在活动的onResume()调用start(true)。没有仔细看说明文档。想顺便请教一个问题，恢复轮播的时候，restoreBanner()和startBanner()方法的实现是一样，为啥要提供两个方法呀？

**Comment by 7449** [comment]
这个.....忘了改成private了，然后就一直都没改
