### ISSUE TITLE
刷新layout怎么做

### ISSUE THREAD

**Issue by HeJingWei** [7449/BannerLayout#7]
比如请求到的网络图片发生了改变，图片张树和指示原点都需要改变

**Comment by 7449** [comment]
initBanner不应该在请求网络成功之后调用的吗? 那你每次请求成功后都会刷新一次bannerLayout
例如这样：

   @Override
    public void onRefresh() {
        swipeRefreshLayout.setRefreshing(true);
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                bannerLayout.initListResources(initSystemNetWorkModel()).initTips().start(true);
                swipeRefreshLayout.setRefreshing(false);
            }
        }, 3000);
    }

每次刷新一次数据都会得到更新，这个问题并不成立

**Comment by HeJingWei** [comment]
是在网络请求之后调用，但有时候网络出错了没有走success，在切换到这个fragment 的时候需要重新请求网络获取数据，这个时候如果调用initBanner是会刷新bannerLayout吗？

**Comment by 7449** [comment]
既然是网络请求，banner的第一次初始化应该是放在网络请求成功之后，之后每次刷新数据banner都会自动更新，如果网络error，页面数据没有更新，banner网络请求之前什么样子失败之后还是什么样子

**Comment by HeJingWei** [comment]
那我在每次fragment show出来的时候 都去请求一次网络然后调用initBanner 这样做可以吗

**Comment by 7449** [comment]
bannerLayout.initListResources(initSystemNetWorkModel()).initTips().start(true); 
这句代码是放在网络success之后的，那么你每次网络成功了都会调用一遍。
说的再多都不如你亲自试一遍。

**Comment by HeJingWei** [comment]
嗯，我试了，主要还是想确定一下会刷新数据和指示圆点，谢谢啦
