### ISSUE TITLE
和recyclerView嵌套的滑动

### ISSUE THREAD

**Issue by HeJingWei** [7449/BannerLayout#9]
库很清楚很好用，但是在当作recyclerView的头部的时候，左右快速滑动，会带动上下滑动，希望能改动一下触摸事件 :)

**Comment by 7449** [comment]
https://github.com/7449/BannerLayout/blob/master/app/src/main/java/com/bannersimple/simple/RefreshActivity.java

sample有完整示例，滑动没有带动RecyclerView 的 滑动事件

**Comment by HeJingWei** [comment]
是将banner作为RecyclerView的一个item来解决吗

**Comment by 7449** [comment]
使用之前先运行一下sample，查看一下我提供的示例，我已经尽可能的提供了所有的使用示例，你这个情况 可以查看下 refresh 目录下的代码示例

**Comment by 7449** [comment]
https://github.com/7449/BannerLayout/blob/master/app/src/main/java/com/bannersimple/refresh/RefreshAdapter.java
